version: '3.8'

services:
  # FastAPI Backend
  backend:
    build: .
    container_name: legalai_backend
    environment:
      - SUPABASE_URL=${SUPABASE_URL}
      - SUPABASE_KEY=${SUPABASE_KEY}
      - SUPABASE_SERVICE_ROLE_KEY=${SUPABASE_SERVICE_ROLE_KEY}
      - ENVIRONMENT=development
      - SECRET_KEY=your-secret-key-change-in-production
      - GEMINI_API_KEY=${GEMINI_API_KEY}
    ports:
      - "8000:8000"
    volumes:
      - ./app:/app/app
      - backend_data:/app/data
      - backend_models:/app/models
      - backend_uploads:/app/uploads
    networks:
      - legalai_network
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8000/health"]
      interval: 30s
      timeout: 10s
      retries: 3

  # Nginx reverse proxy (optional, for production)
  nginx:
    image: nginx:alpine
    container_name: legalai_nginx
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf
      - ./ssl:/etc/nginx/ssl
    depends_on:
      - backend
    networks:
      - legalai_network
    restart: unless-stopped

volumes:
  backend_data:
    driver: local
  backend_models:
    driver: local
  backend_uploads:
    driver: local

networks:
  legalai_network:
    driver: bridge